# Data Generator

Generating more realistic data

In [1]:
# helper functions
from datagen_helper import generate_pd_df

import pandas as pd

In [5]:
df_pd = generate_pd_df(20)

df_pd.to_csv('transactions-small.csv', sep='|', index=False)
print (f'wrote {rows} rows to "transactions-small.csv"')

df_pd

,id,timestamp,mti,card_number,amount_customer,merchant_type,merchant_id,merchant_address,ref_id,amount_merchant,response_code
0,95ec1146-7fa5-4478-baea-6cc750d4fc49,2019-11-10 05:11:31.186,0100,4496798378639312,70.92,7911,0,"Super Bakery, 55 Hillview St, San Jose, NM, USA",,NaN,NaN
1,2342f35b-bf70-4367-a055-f776e3b59745,2019-11-10 05:11:31.689,0110,4496798378639312,70.92,7911,0,"Super Bakery, 55 Hillview St, San Jose, NM, USA",95ec1146-7fa5-4478-baea-6cc750d4fc49,68.79,00
2,be98c6d6-d096-4d0d-aeb4-4df8a5e5ddec,2018-07-27 16:21:27.487,0100,4445840638571636,37.33,4689,99,"Sun Shine Bakery, 15 Market St, Foster City, C...",,NaN,NaN
3,6bd58a94-6cde-433e-bd1a-d506df6929e4,2018-07-27 16:21:28.966,0110,4445840638571636,37.33,4689,99,"Sun Shine Bakery, 15 Market St, Foster City, C...",be98c6d6-d096-4d0d-aeb4-4df8a5e5ddec,36.21,08
4,da36343e-6f8c-4407-81f3-d7fa24bd76df,2016-07-06 08:37:59.203,0100,4083835431254320,42.61,3424,0,"Awesome Nursery, 181 Market St, San Mateo, MA,...",,NaN,NaN
5,e8c184a2-acf1-4642-a1ef-738d2daa2ad0,2016-07-06 08:38:01.834,0110,4083835431254320,42.61,3424,0,"Awesome Nursery, 181 Market St, San Mateo, MA,...",da36343e-6f8c-4407-81f3-d7fa24bd76df,41.33,00
6,7cc1938e-a984-46f8-9512-e5fbf8e8e372,2017-01-31 18:53:23.955,0100,4465239124655862,71.70,1728,87,"Awesome Restaurant, 358 Alameda ave, San Jose,...",,NaN,NaN
7,a5546ac6-2f1f-4805-ad23-adef43674c08,2017-01-31 18:53:25.745,0110,4465239124655862,71.70,1728,87,"Awesome Restaurant, 358 Alameda ave, San Jose,...",7cc1938e-a984-46f8-9512-e5fbf8e8e372,69.55,00
8,c9661f8b-9197-433e-986c-d0c1c04a8630,2016-07-18 03:38:03.374,0100,4703513371921687,80.12,6226,0,"Awesome Nursery, 164 Main st, San Jose, CO, USA",,NaN,NaN
9,a55023ca-a8bb-4b64-a995-fac0aa8f17bf,2016-07-18 03:38:05.215,0110,4703513371921687,80.12,6226,0,"Awesome Nursery, 164 Main st, San Jose, CO, USA",c9661f8b-9197-433e-986c-d0c1c04a8630,77.72,00
10,ec01c32a-8d43-49c9-a3cb-15262278c1d5,2019-03-20 03:21:37.456,0100,4145507259339284,78.48,9293,0,"Best Restaurant, 685 Market St, Redwood City, ...",,NaN,NaN
11,03253831-f1e7-40e6-aa60-7db6a2716d68,2019-03-20 03:21:38.126,0110,4145507259339284,78.48,9293,0,"Best Restaurant, 685 Market St, Redwood City, ...",ec01c32a-8d43-49c9-a3cb-15262278c1d5,76.13,00
12,48731090-e767-4e1e-8a15-972f20505109,2015-04-09 01:13:13.519,0100,4406011998537272,15.52,7597,19,"Four Seasons Toys, 266 Beach rd, San Francisco...",,NaN,NaN
13,644c1fe9-6298-47c2-9428-29f5caa20125,2015-04-09 01:13:15.468,0110,4406011998537272,15.52,7597,19,"Four Seasons Toys, 266 Beach rd, San Francisco...",48731090-e767-4e1e-8a15-972f20505109,15.05,08
14,5a24bb79-1475-490d-93f1-17e2463bb147,2019-06-10 21:01:55.025,0100,4676643985511589,1.68,3080,70,"Best Donuts, 945 Main st, San Jose, DE, USA",,NaN,NaN
15,b80e5dfd-f39c-4f17-b715-07903f6036ab,2019-06-10 21:01:56.840,0110,4676643985511589,1.68,3080,70,"Best Donuts, 945 Main st, San Jose, DE, USA",5a24bb79-1475-490d-93f1-17e2463bb147,1.63,00
16,1c1936e0-dfdf-4bc1-9f43-5e4a6b43b58d,2019-11-01 08:58:52.969,0100,4438409550898354,88.76,5552,75,"Best Nursery, 42 Hillview St, Redwood City, ME...",,NaN,NaN
17,f92bb3fb-9312-4c4d-9216-633732f9edee,2019-11-01 08:58:53.812,0110,4438409550898354,88.76,5552,75,"Best Nursery, 42 Hillview St, Redwood City, ME...",1c1936e0-dfdf-4bc1-9f43-5e4a6b43b58d,86.10,00
18,e1e602ec-4dda-47c8-a988-74de09454945,2015-07-07 00:30:59.352,0100,4365013520165721,54.75,0702,0,"Star Flowers, 751 Beach rd, Redwood City, NY, USA",,NaN,NaN
19,5e25e0a7-148d-453b-a96c-a266e9d0ca13,2015-07-07 00:31:01.527,0110,4365013520165721,54.75,0702,0,"Star Flowers, 751 Beach rd, Redwood City, NY, USA",e1e602ec-4dda-47c8-a988-74de09454945,53.11,00

## Create a Spark DataFrame

In [3]:
## Init Spark
import os, sys

this_dir = os.path.abspath('')
parent_dir = os.path.dirname(this_dir)
grand_parent_dir = os.path.dirname(parent_dir)
    
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from init_spark import init_spark

spark = init_spark()

Initializing Spark...
Spark found in :  /home/sujee/apps/spark
Spark config:
	 spark.app.name=TestApp
	spark.master=local[*]
	executor.memory=2g
	spark.sql.warehouse.dir=/tmp/tmppy3mkv6u
	some_property=some_value
Spark UI running on port 4040

In [4]:
import pyspark
from pyspark.sql.types import ArrayType, IntegerType, LongType, StringType, FloatType, TimestampType, StructType, StructField

my_schema = StructType([
                       StructField("id", StringType(), True),
                       StructField("timestamp", StringType(), True),
                       StructField("mti", StringType(), True),
                       StructField("card_number", StringType(), True),
                       StructField("amount_customer", FloatType(), True),
                       StructField("merchant_type", StringType(), True),
                       StructField("merchant_id", IntegerType(), True),
                       StructField("merchant_address", StringType(), True),
                       StructField("ref_id", StringType(), True),
                       StructField("amount_merchant", FloatType(), True),
                       StructField("response_code", StringType(), True),
                      ])


spark_df = spark.createDataFrame(df_pd, schema=my_schema)
spark_df.show(truncate=True)

+--------------------+--------------------+----+----------------+---------------+-------------+-----------+--------------------+--------------------+---------------+-------------+
|                  id|           timestamp| mti|     card_number|amount_customer|merchant_type|merchant_id|    merchant_address|              ref_id|amount_merchant|response_code|
+--------------------+--------------------+----+----------------+---------------+-------------+-----------+--------------------+--------------------+---------------+-------------+
|f8471810-10f9-4e1...|2019-11-23 15:11:...|0100|4107005149414370|          58.56|         2131|          0|Best Liquors, 7 A...|                    |            NaN|          NaN|
|3fbeefb1-cbda-411...|2019-11-23 15:11:...|0110|4107005149414370|          58.56|         2131|          0|Best Liquors, 7 A...|f8471810-10f9-4e1...|           56.8|           08|
|e59d130c-054b-4bc...|2020-06-26 10:42:...|0100|4732422479122396|           7.45|         1196|          0|Summer Winds Donu...|                    |            NaN|          NaN|
|d16f0ada-dcce-449...|2020-06-26 10:42:...|0110|4732422479122396|           7.45|         1196|          0|Summer Winds Donu...|e59d130c-054b-4bc...|           7.23|           00|
|037e6143-21bb-478...|2020-08-13 12:11:...|0100|4408274979393975|          84.61|         1817|         31|First Donuts, 593...|                    |            NaN|          NaN|
|1d295664-b117-436...|2020-08-13 12:11:...|0110|4408274979393975|          84.61|         1817|         31|First Donuts, 593...|037e6143-21bb-478...|          82.07|           00|
|27090324-c68c-4b5...|2018-11-22 21:59:...|0100|4750189971467571|          67.08|         7403|         76|Awesome Bakery, 2...|                    |            NaN|          NaN|
|35eebac7-2d95-41f...|2018-11-22 21:59:...|0110|4750189971467571|          67.08|         7403|         76|Awesome Bakery, 2...|27090324-c68c-4b5...|          65.07|           00|
|03374aea-c1cf-4db...|2019-01-28 11:56:...|0100|4496256501715163|           93.9|         6833|         45|First Toys, 576 A...|                    |            NaN|          NaN|
|0480d68a-9027-411...|2019-01-28 11:56:...|0110|4496256501715163|           93.9|         6833|         45|First Toys, 576 A...|03374aea-c1cf-4db...|          91.08|           00|
+--------------------+--------------------+----+----------------+---------------+-------------+-----------+--------------------+--------------------+---------------+-------------+